### PR TITLE
Deactivate TikTok for WooCommerce if Business is active

### LINKED ISSUE #1373: Deactivate tiktok-for-woocommerce if tiktok-for-business is active
A user is on the business plan and has installed `tiktok-for-business`

When they upgrade to the ecommerce plan, we install `tiktok-for-woocommerce` which causes a fatal error

```
Fatal error: Cannot declare class Tt4b_Mapi_Class, because the name is already in use in /wordpress/plugins/tiktok-for-woocommerce/1.2.2/mapi/Tt4b_Mapi_Class.php on line 15
```

See discussion in Slack p1700391999867779-slack-C02Q5922VGC

Those two plugins are the same, but one is on wccom and the other on work, with different slugs.

I suggest we deactivate `tiktok-for-woocommerce` if both plugins are installed and active

### PR DESCRIPTION
**Pull request by PanosSynetos**
### Changes proposed in this Pull Request:

Closes #1373 .

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

- [ ] Have you followed the [Writing high-quality testing instructions guide](https://github.com/woocommerce/woocommerce/wiki/Writing-high-quality-testing-instructions)?

SSH into your dev site and `tail -f /tmp/php-errors` - Monitor for warnings, fatals related to this PR

### Master Branch uploaded on dev site

1. Make sure your site has both [tiktok-for-woocommerce.zip](https://github.com/Automattic/wc-calypso-bridge/files/14037316/tiktok-for-woocommerce.zip) and [tiktok-for-business.1.2.3.zip](https://github.com/Automattic/wc-calypso-bridge/files/14037336/tiktok-for-business.1.2.3.zip)
2. Using CLI activate both plugins
3. `wp --skip-plugins plugin activate tiktok-for-business`
4. `wp --skip-plugins plugin activate tiktok-for-woocommerce`
5. `wp plugin list` should cause a fatal error `Cannot declare class Tt4b_Mapi_Class, because the name is already in use`

### Checkout and upload this branch on dev site
1. `wp plugin list` should not return a fatal error
2. `tiktok-for-woocommerce` should be deactivated
3. Try breaking it (activate plugins in different order, think out of the box)

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: class-wc-calypso-bridge.php [hunk 1]
```diff
@@ -74,10 +74,28 @@ function_exists( 'WC' ) &&
...
 	}
 
+	/**
+	 * Deactivate TikTok for WooCommerce if both TikTok for WooCommerce and Business are active (they are the same).
+	 *
+	 * @since x.x.x
+	 *
+	 */
+	public function deactivate_duplicate_tiktok() {
+		$active_plugins  = get_option( 'active_plugins' );
```
Comment (xristos3490) [inline class-wc-calypso-bridge.php:89]: I'd suggest using a more defensive approach here to avoid regressions:

```suggestion
		$active_plugins  = (array) get_option( 'active_plugins', array() );
```

**Review by xristos3490 — CHANGES_REQUESTED** [review]

File: class-wc-calypso-bridge.php (hunk 1 above)
Comment (PanosSynetos) [reply class-wc-calypso-bridge.php]: Thanks Chris! I like the way you think :)

**Review by xristos3490 — APPROVED** [review]
Looks good 👌

**Review by dakota — APPROVED** [review]
LGTM!

Tested, and does as advertised
