### PR TITLE
Register TaxJar settings page.

### LINKED ISSUE #533: Map TaxJar Settings Tab
Currently when navigating to the TaxJar settings page, the calypsoify styling is not properly being applied:

image

To reproduce, click on TaxJar in the sidebar of an ecomm site, or go to `/wp-admin/admin.php?page=wc-settings&tab=taxjar-integration` - thinking we just need to add the appropriate page registration.

### PR DESCRIPTION
**Pull request by timmyc**
Fixes #533 

This branch adds in the logic to register the TaxJar settings page so it will properly render the Woo nav in calypsoify mode.

__Before__
taxjar-before

__After__
taxjar-after

__To Test__
- Install the TaxJar plugin from the wp.org repo if not already installed.
- On `master` of `wc-calypso-bridge` visit /wp-admin/admin.php?page=wc-settings&tab=taxjar-integration&calypsoify=1`, and verify a calypsoified version of the Woo Settings page is shown, but the sidebar is not showing the Woo Nav.
- Checkout this branch
- Refresh the page and verify it looks like the "after" screen shot above.

### CODE REVIEW

File: includes/connect/taxjar-simplified-taxes-for-woocommerce.php [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+ * Register the TaxJar Settings Page.
+ *
+ * @package WC_Calypso_Bridge
+ * @since 1.1.5
+ * @version 1.0.0
+ */
+
+wc_calypso_bridge_connect_page(
+	array(
+		'screen_id' => 'woocommerce_page_wc-settings-taxjarz-integration',
```
Comment (rrennick) [inline includes/connect/taxjar-simplified-taxes-for-woocommerce.php:12]: Typo: `taxjarz` should be `taxjar`.

Comment (timmyc) [reply includes/connect/taxjar-simplified-taxes-for-woocommerce.php]: Good catch! fixed in 
88aa8a6
