### PR TITLE
Remove Jetpack Connection step in tax task on a free trial 

### LINKED ISSUE #1146: Tax Task list is broken
### Prerequisites

- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The tax task list item appears to be broken for Woo Express sites. If you choose to use WooCommerce Tax, we're showing the Jetpack steps which are not needed. The address should already be set to enable Tax by default. 

We should also decide whether we should show Avalara.

### Expected behavior

-

### Actual behavior

-

### Steps to reproduce

-

### WordPress Environment

-

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by moon0326**
### Changes proposed in this Pull Request:

Closes #1146 

This PR removes Jetpack connection step in WooCommerce Tax setup step as atomic sites are already connected to Jetpack. 

- [ ] This PR is a very minor change/addition and does not require testing instructions (if checked you can ignore/remove the next section).

### How to test the changes in this Pull Request:

1. Checkout this branch in your setup and make sure Jetpack is connected.
2. Click `Add tax rates` task in WooCommerce Home
3. Click `WooCommerce Tax`
4. Confirm the changes

Screen Shot 2023-07-30 at 2 05 56 PM
Screen Shot 2023-07-30 at 2 05 45 PM

### Other information:

-   [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
-   [ ] Have you written new tests for your changes, as applicable?

### FOR PR REVIEWER ONLY:

-   [ ] I have reviewed that everything is sanitized/escaped appropriately for any SQL or XSS injection possibilities. I made sure Linting is not ignored or disabled.

### CODE REVIEW

File: src/free-trial/tax/woocommerce-tax/setup.tsx [hunk 1]
```diff
@@ -101,25 +102,14 @@ export const Setup: React.FC< SetupProps > = ( {
...
-			description: __(
-				'Jetpack and WooCommerce Tax allow you to automate sales tax calculations',
-				'woocommerce'
-			),
-			content: <Plugins { ...stepProps } />,
-		},
 		{
 			key: 'connect',
-			label: __( 'Connect your store', 'woocommerce' ),
+			label: __( 'Automate Taxes', 'woocommerce' ),
```
Comment (chihsuan) [inline src/free-trial/tax/woocommerce-tax/setup.tsx:107]: AFAIK, we don't handle bridge i18n properly right now but I think we should use `wc-calypso-bridge` text domain here. What do you think?

File: assets/css/free-trial-admin.css [hunk 2]
```diff
@@ -43,3 +43,8 @@
 	.woocommerce-experimental-list__item.complete {
 	color: var( --wp-admin-theme-color );
 }
+
+.woocommerce-task-tax__success {
+	flex-direction: row !important;
+	padding: 0!important;
```
Comment (chihsuan) [inline assets/css/free-trial-admin.css:49]: Nit:

```suggestion
	padding: 0 !important;
```

File: src/free-trial/tax/woocommerce-tax/setup.tsx [hunk 3]
```diff
@@ -101,25 +102,14 @@ export const Setup: React.FC< SetupProps > = ( {
 			),
 			content: <StoreLocation { ...stepProps } />,
```
Comment (chihsuan) [inline src/free-trial/tax/woocommerce-tax/setup.tsx:103]: I previously changed all the fields to mandatory in [this Core PR](https://github.com/woocommerce/woocommerce/pull/38137) because [all fields are required to enable tax automation](https://github.com/Automattic/wc-calypso-bridge/blob/520f3e6de237f3556f0ab64d57b40648e9347a57/src/free-trial/tax/woocommerce-tax/index.tsx#L53). I think we should also modify it here, but I'm okay if we do it in a follow-up PR.

**Review by chihsuan — COMMENTED** [review]
Tested well. Just some comments.

**Review by ilyasfoo — APPROVED** [review]
Tested well! LGTM 🚢 

Edit: Missed changelog in readme.txt, but otherwise LGTM!

**Comment by moon0326** [comment]
Thanks @ilyasfoo and @chihsuan 

I'll wait for Veronica's feedback and make a few more changes soon.

**Comment by moon0326** [comment]
@chihsuan @ilyasfoo I've commited https://github.com/Automattic/wc-calypso-bridge/pull/1247/commits/e7b2d2d0f6313d0ed17ad19f472d263a7d845c75 to reflect Veronica's [suggestion](https://github.com/Automattic/wc-calypso-bridge/issues/1146#issuecomment-1662183246). Could you please take a look at it again?

**Comment by moon0326** [comment]
@chihsuan @ilyasfoo Could you please test it on a free trial site if you get a chance 🙏 ? I'm having a hard time setting up a free trial with SSh access.

**Review by chihsuan — APPROVED** [review]
> Could you please test it on a free trial site if you get a chance 🙏 ? I'm having a hard time setting up a free trial with SSh access.

Sure, tested well! 👍 

Screenshot 2023-08-04 at 12 04 28

**Comment by ilyasfoo** [comment]
Apologies for the late re-review, while reviewing the release I found the interface looked like this instead:

image

I'm not sure how @chihsuan was able to see the correct UI 🤔 . I'll attempt a simple fix anyway.

**Comment by ilyasfoo** [comment]
Fix https://github.com/Automattic/wc-calypso-bridge/pull/1261, if you can take a look @chihsuan and @moon0326 it'll be great 🙏
